export const L = {
  // Auth
  appName: 'SuuqPOS',
  tagline: 'Dukaankaaga — gacantaada',
  phoneLabel: 'Lambarka Telefoonka',
  phoneHint: '061 234 5678',
  pinLabel: 'PIN (4 lambar)',
  pinHint: 'Geli PIN-kaaga',
  setPinLabel: 'Sameyso PIN',
  confirmPin: 'Ku celi PIN-ka',
  register: 'Diiwaan geli',
  unlock: 'Fur',
  wrongPin: 'PIN-ku khalad yahay',
  pinMismatch: 'PIN-yadu is ma aha',

  // Tabs
  tabInventory: 'Alaabta',
  tabSell: 'Iib',
  tabSales: 'Iibkii',
  tabAccount: 'Xisaab',

  // Inventory
  inventory: 'Kaydhka',
  addProduct: 'Alaab cusub',
  editProduct: 'Wax ka badal',
  productName: 'Magaca',
  productNameHint: 'Tusaale: Bariis 5kg',
  sellPrice: 'Qiimaha iibka',
  buyPrice: 'Qiimaha iibsiga',
  quantity: 'Tirada',
  category: 'Qaybta',
  save: 'Kaydi',
  saved: 'Waa la kaydiyay',
  delete: 'Tirtir',
  deleteConfirm: 'Ma hubtaa inaad tirtirto?',
  cancel: 'Dib u noqo',
  noProducts: 'Alaab ma jirto',
  noProductsHint: 'Ku dar alaabta dukaankaaga',
  all: 'Dhammaan',
  pcs: 'xabo',
  addStock: 'Ku dar',
  removeStock: 'Ka jar',
  stockIn: 'Soo geli',
  stockOut: 'Ka bixi',
  profit: 'Faa\'iido',

  // POS
  searchHint: 'Raadi alaab...',
  emptyCart: 'Dooro alaab',
  total: 'Wadarta',
  cash: 'Lacag',
  evc: 'EVC Plus',
  saleDone: 'Waa la iibiyay!',

  // Sales
  sales: 'Iibkii',
  noSales: 'Iib ma jiro weli',
  receipt: 'Rasiidh',
  today: 'Maanta',
  thisWeek: 'Todobaad',
  thisMonth: 'Bil',
  revenue: 'Dakhli',
  totalSales: 'Iibkii',
  report: 'Warbixin',
  generateReport: 'Soo saaro warbixin',

  // Settings
  settings: 'Xisaab',
  shopName: 'Dukaanka',
  phone: 'Telefoon',
  changePin: 'Badal PIN',
  version: 'v1.0',
  confirm: 'Xaqiiji',
} as const;
